// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// Wails bridge types for Darvin-Resume

import {model} from './models';
import {ai} from './models';

export function Greet(arg1: string): Promise<string>;

export function CreateResume(arg1: string): Promise<model.Resume>;
export function GetResume(arg1: string): Promise<model.Resume>;
export function ListResumes(): Promise<Array<model.ResumeListItem>>;
export function UpdateResume(arg1: string, arg2: string): Promise<void>;
export function DeleteResume(arg1: string): Promise<void>;
export function UpdateResumeModule(arg1: string, arg2: string, arg3: string): Promise<void>;
export function RenameResume(arg1: string, arg2: string): Promise<void>;
export function DuplicateResume(arg1: string): Promise<model.Resume>;
export function RestoreResume(arg1: string): Promise<void>;
export function PermanentDeleteResume(arg1: string): Promise<void>;
export function ListDeletedResumes(): Promise<Array<model.ResumeListItem>>;

// AI Bridge Methods
export function GetAIConfig(): Promise<Record<string, any>>;
export function SaveAIConfig(arg1: Record<string, any>): Promise<void>;
export function ValidateAPIKey(arg1: string, arg2: string): Promise<boolean>;
export function AISendMessage(arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<string>;
export function AISendMessageSync(arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<string>;
export function AISendChatMessage(arg1: string, arg2: string, arg3: string, arg4: Array<ai.ChatMessage>, arg5: string): Promise<string>;
export function AICancelOperation(arg1: string): Promise<void>;
export function GetChatHistory(arg1: string): Promise<Array<ai.ChatMessage>>;
export function SaveChatMessage(arg1: ai.ChatMessage): Promise<void>;
export function ClearChatHistory(arg1: string): Promise<void>;

// Template Methods
export function UpdateResumeTemplate(arg1: string, arg2: string): Promise<void>;
export function UpdateResumeCustomCSS(arg1: string, arg2: string): Promise<void>;

// Export Methods
export function ExportPDFFromHTML(arg1: string, arg2: string): Promise<string>;
export function ShowSaveDialog(arg1: Record<string, any>): Promise<Record<string, any>>;

// Snapshot Methods (EXPT-05 ~ EXPT-09)
export function CreateSnapshot(arg1: string, arg2: string, arg3: string, arg4: string): Promise<model.Snapshot>;
export function ListSnapshots(arg1: string): Promise<Array<model.SnapshotListItem>>;
export function GetSnapshot(arg1: string): Promise<model.Snapshot>;
export function DiffSnapshots(arg1: string, arg2: string): Promise<model.DiffResult>;
export function RollbackToSnapshot(arg1: string, arg2: string): Promise<model.Snapshot>;
export function DeleteSnapshot(arg1: string): Promise<void>;
export function GetSnapshotMarkdown(arg1: string): Promise<Array<string>>;
