// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AICancelOperation(arg1) {
  return window['go']['main']['App']['AICancelOperation'](arg1);
}

export function AISendChatMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AISendChatMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function AISendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AISendMessage'](arg1, arg2, arg3, arg4);
}

export function AISendMessageSync(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AISendMessageSync'](arg1, arg2, arg3, arg4);
}

export function ClearChatHistory(arg1) {
  return window['go']['main']['App']['ClearChatHistory'](arg1);
}

export function CreateResume(arg1) {
  return window['go']['main']['App']['CreateResume'](arg1);
}

export function CreateSnapshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSnapshot'](arg1, arg2, arg3, arg4);
}

export function DeleteResume(arg1) {
  return window['go']['main']['App']['DeleteResume'](arg1);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function DiffSnapshots(arg1, arg2) {
  return window['go']['main']['App']['DiffSnapshots'](arg1, arg2);
}

export function DuplicateResume(arg1) {
  return window['go']['main']['App']['DuplicateResume'](arg1);
}

export function ExportPDFFromHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportPDFFromHTML'](arg1, arg2);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetResume(arg1) {
  return window['go']['main']['App']['GetResume'](arg1);
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function GetSnapshotMarkdown(arg1) {
  return window['go']['main']['App']['GetSnapshotMarkdown'](arg1);
}

export function GetShortcuts() {
  return window['go']['main']['App']['GetShortcuts']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDeletedResumes() {
  return window['go']['main']['App']['ListDeletedResumes']();
}

export function ListResumes() {
  return window['go']['main']['App']['ListResumes']();
}

export function ListSnapshots(arg1) {
  return window['go']['main']['App']['ListSnapshots'](arg1);
}

export function PermanentDeleteResume(arg1) {
  return window['go']['main']['App']['PermanentDeleteResume'](arg1);
}

export function RenameResume(arg1, arg2) {
  return window['go']['main']['App']['RenameResume'](arg1, arg2);
}

export function RestoreResume(arg1) {
  return window['go']['main']['App']['RestoreResume'](arg1);
}

export function RollbackToSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RollbackToSnapshot'](arg1, arg2);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveChatMessage(arg1) {
  return window['go']['main']['App']['SaveChatMessage'](arg1);
}

export function SetShortcuts(arg1) {
  return window['go']['main']['App']['SetShortcuts'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShowSaveDialog(arg1) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1);
}

export function UpdateResume(arg1, arg2) {
  return window['go']['main']['App']['UpdateResume'](arg1, arg2);
}

export function UpdateResumeCustomCSS(arg1, arg2) {
  return window['go']['main']['App']['UpdateResumeCustomCSS'](arg1, arg2);
}

export function UpdateResumeModule(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateResumeModule'](arg1, arg2, arg3);
}

export function UpdateResumeTemplate(arg1, arg2) {
  return window['go']['main']['App']['UpdateResumeTemplate'](arg1, arg2);
}

export function ValidateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['ValidateAPIKey'](arg1, arg2);
}
