// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AICancelOperation(arg1) {
  return window['go']['main']['App']['AICancelOperation'](arg1);
}

export function AISendChatMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AISendChatMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function AISendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AISendMessage'](arg1, arg2, arg3, arg4);
}

export function AISendMessageSync(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AISendMessageSync'](arg1, arg2, arg3, arg4);
}

export function ClearChatHistory(arg1) {
  return window['go']['main']['App']['ClearChatHistory'](arg1);
}

export function CreateResume(arg1) {
  return window['go']['main']['App']['CreateResume'](arg1);
}

export function DeleteResume(arg1) {
  return window['go']['main']['App']['DeleteResume'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetResume(arg1) {
  return window['go']['main']['App']['GetResume'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListResumes() {
  return window['go']['main']['App']['ListResumes']();
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveChatMessage(arg1) {
  return window['go']['main']['App']['SaveChatMessage'](arg1);
}

export function UpdateResume(arg1, arg2) {
  return window['go']['main']['App']['UpdateResume'](arg1, arg2);
}

export function UpdateResumeModule(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateResumeModule'](arg1, arg2, arg3);
}

export function ValidateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['ValidateAPIKey'](arg1, arg2);
}
