// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';
import {model} from '../models';

export function AICancelOperation(arg1:string):Promise<void>;

export function AISendChatMessage(arg1:string,arg2:string,arg3:string,arg4:Array<ai.ChatMessage>,arg5:string):Promise<string>;

export function AISendMessage(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function AISendMessageSync(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function ClearChatHistory(arg1:string):Promise<void>;

export function CreateResume(arg1:string):Promise<model.Resume>;

export function DeleteResume(arg1:string):Promise<void>;

export function DuplicateResume(arg1:string):Promise<model.Resume>;

export function GetAIConfig():Promise<Record<string, any>>;

export function GetChatHistory(arg1:string):Promise<Array<ai.ChatMessage>>;

export function GetResume(arg1:string):Promise<model.Resume>;

export function Greet(arg1:string):Promise<string>;

export function ListDeletedResumes():Promise<Array<model.ResumeListItem>>;

export function ListResumes():Promise<Array<model.ResumeListItem>>;

export function PermanentDeleteResume(arg1:string):Promise<void>;

export function RenameResume(arg1:string,arg2:string):Promise<void>;

export function RestoreResume(arg1:string):Promise<void>;

export function SaveAIConfig(arg1:Record<string, any>):Promise<void>;

export function SaveChatMessage(arg1:ai.ChatMessage):Promise<void>;

export function UpdateResume(arg1:string,arg2:string):Promise<void>;

export function UpdateResumeCustomCSS(arg1:string,arg2:string):Promise<void>;

export function UpdateResumeModule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateResumeTemplate(arg1:string,arg2:string):Promise<void>;

export function ValidateAPIKey(arg1:string,arg2:string):Promise<boolean>;
