// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';
import {model} from '../models';

export function AICancelOperation(arg1:string):Promise<void>;

export function AISendChatMessage(arg1:string,arg2:string,arg3:string,arg4:Array<ai.ChatMessage>,arg5:string):Promise<string>;

export function AISendMessage(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function AISendMessageSync(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function ClearChatHistory(arg1:string):Promise<void>;

export function CreateManualBackup(arg1:string):Promise<string>;

export function CreateResume(arg1:string):Promise<model.Resume>;

export function CreateSnapshot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.Snapshot>;

export function DeleteResume(arg1:string):Promise<void>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function DiffSnapshots(arg1:string,arg2:string):Promise<model.DiffResult>;

export function DuplicateResume(arg1:string):Promise<model.Resume>;

export function ExportBackupToPath(arg1:string,arg2:string):Promise<string>;

export function ExportPDFFromHTML(arg1:string,arg2:string):Promise<string>;

export function GetAIConfig():Promise<Record<string, any>>;

export function GetAutoBackupSettings():Promise<string>;

export function GetBackupDir():Promise<string>;

export function GetChatHistory(arg1:string):Promise<Array<ai.ChatMessage>>;

export function GetResume(arg1:string):Promise<model.Resume>;

export function GetSnapshot(arg1:string):Promise<model.Snapshot>;

export function GetSnapshotMarkdown(arg1:string):Promise<string>;

export function GetTheme():Promise<string>;

export function GetShortcuts():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListBackups():Promise<string>;

export function ListDeletedResumes():Promise<Array<model.ResumeListItem>>;

export function ListResumes():Promise<Array<model.ResumeListItem>>;

export function ListSnapshots(arg1:string):Promise<Array<model.SnapshotListItem>>;

export function PermanentDeleteResume(arg1:string):Promise<void>;

export function RenameResume(arg1:string,arg2:string):Promise<void>;

export function RestoreFromBackup(arg1:string,arg2:string):Promise<void>;

export function RestoreResume(arg1:string):Promise<void>;

export function RollbackToSnapshot(arg1:string,arg2:string):Promise<model.Snapshot>;

export function SaveAIConfig(arg1:Record<string, any>):Promise<void>;

export function SaveChatMessage(arg1:ai.ChatMessage):Promise<void>;

export function SetAutoBackupSettings(arg1:boolean,arg2:string):Promise<void>;

export function SetShortcuts(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function ShowOpenBackupDialog():Promise<string>;

export function ShowSaveBackupDialog():Promise<string>;

export function ShowSaveDialog(arg1:Record<string, any>):Promise<Record<string, any>>;

export function UpdateResume(arg1:string,arg2:string):Promise<void>;

export function UpdateResumeCustomCSS(arg1:string,arg2:string):Promise<void>;

export function UpdateResumeModule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateResumeTemplate(arg1:string,arg2:string):Promise<void>;

export function ValidateAPIKey(arg1:string,arg2:string):Promise<boolean>;
